name: TakeMeHome
version: '1.1.0-SNAPSHOT'
main: com.csmcclain.takeMeHome.TakeMeHome
api-version: '1.21.0'
commands:
  home:
    description: Take you home
    usage: /home
  sethome:
    description: Adds a location to the player's home locations
    usage: "Usage: /sethome <home-name>"
  listhome:
    description: Lists player's home locations
    usage: "Usage: /listhomes"
  updatehome:
    description: Updates player's home with new location
    usage: "Usage: /updatehome <home>"
  removehome:
    description: Removes home with <name> from players home
    usage: "Usage: /removehome <home>"
  setdefaulthome:
    description: Sets a player's default home
    usage: "Usage: /setdefaulthome <home>"
  removedefaulthome:
    description: Removes a player's default home
    usage: "Usage: /removedefaulthome"
  back:
    description: Take you back
    usage: /back