name: TakeMeHome
version: '1.1.0-SNAPSHOT'
main: com.csmcclain.takeMeHome.TakeMeHome
api-version: '1.21.1'
commands:
  home:
    description: Takes a player to their specified home
    usage: "Usage: /home <optional home name if not teleporting to default>"
  sethome:
    description: Adds a home to the player's saved homes
    usage: "Usage: /sethome <home>"
  listhome:
    description: Lists player's saved homes
    usage: "Usage: /listhomes"
  updatehome:
    description: Updates a player's home with new location
    usage: "Usage: /updatehome <home>"
  removehome:
    description: Removes home from player's saved homes
    usage: "Usage: /removehome <home>"
  setdefaulthome:
    description: Sets a player's default home
    usage: "Usage: /setdefaulthome <home>"
  removedefaulthome:
    description: Removes a player's default home
    usage: "Usage: /removedefaulthome"
  back:
    description: Takes a player back to the last location they teleported from
    usage: "Usage: /back"